mode = "dark"

accent = "#b99d86"
selection = "#4b3f3a"
muted = "#7d716e"

background = "#2c2525"
dark_background = "#211b1b"
darker_background = "#181414"
lighter_background = "#372f2d"

foreground = "#e6d9db"
dark_foreground = "#72696a"
light_foreground = "#c3b7b8"
bright_foreground = "#e6d9db"

red = "#fd6883"
yellow = "#f9cc6c"
orange = "#fb9a77"
green = "#adda78"
cyan = "#85dacc"
blue = "#b99d86"
magenta = "#a8a9eb"
brown = "#7d4d3b"

bright_red = "#ff8297"
bright_yellow = "#fcd675"
bright_green = "#c8e292"
bright_cyan = "#9bf1e1"
bright_blue = "#b99d86"
bright_magenta = "#bebffd"
